### ISSUE TITLE
nix-mode doesn't declare f as a dependency on MELPA

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nix-mode#135]
`nix-mode` depends on `f` which is not shipped with emacs by default, so it should be declared as a dependency on MELPA.
A plain `emacsWithPackages` will fail upon the `(require 'f)` in `nix-mode` (this is probably not observable a lot since `f` is such a common dependency)'

**Comment by matthewbauer** [comment]
I think that was fixed in:

https://github.com/NixOS/nix-mode/commit/c29b11b6470282df18f1b653f39a7cabe439faba

**Comment by sternenseemann** [comment]
Seems to have updated on melpa as well since.
