### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by ivan-m** [NixOS/nix-mode#30]
Is there any chance that you would put this up on MELPA, etc. for use with package.el?

**Comment by matthewbauer** [comment]
Well I guess we could try to get it in MELPA but nix-mode is already taken by Nix's official nix-mode. I've been hoping we could get Nix to get rid of the old one but haven't got much feedback on NixOS/nix. Either way, you can use this from the repo. Maybe I should rename this to nix2-mode or something like that so it could go in MELPA?

**Comment by ekmecic** [comment]
It'd be awesome if this package were in MELPA since it's super useful but a pain to install. Changing the name would do it, but I think it's best that it replaces the nixpkgs version entirely. 

Perhaps try another PR? I'd love to help in any possible way 😄

**Comment by yorickvP** [comment]
I hacked it into my emacs config with [`emacsWithPackages`](https://github.com/yorickvP/dotfiles/blob/master/nix/.nixpkgs/config.nix#L251-L260). Keep in mind that you also have to [remove the old nix-mode from the load-path](https://github.com/yorickvP/dotfiles/blob/master/emacs/.emacs.d/init.el#L11-L13).

**Comment by matthewbauer** [comment]
It's now availabe in MELPA!
