### ISSUE TITLE
Who provides nix, nix-geiser, nix-guile, and nix-misc

### ISSUE THREAD

**Issue by tarsius** [NixOS/nix-mode#32]
Libraries in this package require the features `nix`, `nix-geiser`, `nix-guile`, and `nix-misc`, but no internal libraries provide these features. Are they provided in some other repository? Or am I overlooking something?

**Comment by vyp** [comment]
I'm not sure, but judging by the names, my guess is these may remnants from the guix.el package or something.. :woman_shrugging:

(Of course, if these do not indeed exist, the lines requiring these features should be removed, I agree.)

**Comment by matthewbauer** [comment]
Yeah, that was some work in progress stuff that I had forgotten about. I'm removing it for now until I can figure out how to integrate it better with nix-mode.el.

**Comment by tarsius** [comment]
Thanks!
