### ISSUE TITLE
Do not set case-fold-search to nil

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nix-mode#33]
```case-fold-search``` is set to ```nil``` and overriding the user's choice. I really like case insensitive search by default.

**Comment by peterhoeg** [comment]
Thanks @matthewbauer but there is one more instance:

**Comment by matthewbauer** [comment]
Okay thanks! I wonder why it was there in the first place?

**Comment by peterhoeg** [comment]
No clue, but I should just have made a PR. Thanks for fixing this!
