### ISSUE TITLE
`==` is incorrectly syntax-highlighted

### ISSUE THREAD

**Issue by taktoa** [NixOS/nix-mode#34]
If you create a Nix file containing a (sub)expression of the form `foo == bar`, where `foo` is an identifier and  `bar` is an expression, `foo` will be syntax-highlighted as an attribute (brown), rather than as an identifier (white). This is likely due to some kind of parsing conflict with the `{ foo = bar; }` syntax, in which it is appropriate to highlight `foo` brown. It would probably be good to add a regression test for this as well, using something similar to the [`haskell-mode` font-lock tests](https://github.com/haskell/haskell-mode/blob/master/tests/haskell-font-lock-tests.el).

**Comment by matthewbauer** [comment]
I've added a test for this specific case. Any other tests would be welcome in a PR!
