### ISSUE TITLE
Indentation issues

### ISSUE THREAD

**Issue by ryantm** [NixOS/nix-mode#36]
I am running nix-mode 20170831.1721 (the latest stable build on MELPA).

I made a file.nix:

```
{ ... } :

let

  a = 1;

b = 2;

in

  a + b;
```

If I go to each line a press tab, this is how it gets indented. The specific problem I have is `b = 2;` does not have the same indentation as `a = 1;`. Also, I noticed that pressing tab with point left of `in` gives this error message:
```
indent-line-to: Wrong type argument: wholenump, -2
```

Please let me know if you need any more information! Thanks for this package!

**Comment by matthewbauer** [comment]
Yes that's a known issue. It's complicated because we need to know how many 'let' or 'in' clauses we have. There's no good way to parse there without having to look through the entire document. I'll look to see if there's a way to fix this.

**Comment by coreyoconnor** [comment]
This indent behavior was, at least in my use, causing more issues than the basic `indent-relative`. 

To force the `indent-relative` indent line function for nix-mode, add to your emacs init:

```
  (eval-after-load 'nix-mode                                                                                                                                                   
    (add-hook 'nix-mode-hook                                                                                                                                                   
              (lambda ()                                                                                                                                                       
                (setq-local indent-line-function #'indent-relative))))                                                                                                         
```

**Comment by Anton-Latukha** [comment]
Just as for every `{` there `}` and for every `(` - `)`. For every `let` must be `in`.

Yes, in many Nix cases that would parse entire file. But I think we have PCs powerful enough to handle this, and it seems that the scope is the same as we have for `{` `}`, that frequently span entire file.

**Comment by CMCDragonkai** [comment]
This is really quite annoying. I really want to make the nix-mode automatically indent every time I create a `let ... in ...` block, and also to automatically indent when we create a lambda `param: ...`.

**Comment by matthewbauer** [comment]
Yes, so now just using indent-relative by default per @coreyoconnor's suggestion. It's definitely possible to get good indentation in Emacs with Nix (Haskell has similar syntax and does it well).

Anyway you can customize the indent with the custom variable ```nix-indent-function```. Help on ```nix-indent-line``` (my own implementation) is very much wanted.

> Yes, in many Nix cases that would parse entire file. But I think we have PCs powerful enough to handle this, and it seems that the scope is the same as we have for { }, that frequently span entire file.

So the issue is more with how Emacs does things. "let" and "in" are not known by Emacs to be tracked in its parsing so we need some other solution.

**Comment by ryantm** [comment]
I cannot reproduce this issue with `nix-mode-20180908.1540` for two reasons. The default `nix-indent-function` is indent-relative, which doesn't know anything about the nix syntax. Also, this is fixed with the `nix-indent-function` set to `nix-indent-line`!

For reference, here is my use-package expression:
```elisp                                                                                                                                                                                                             
(use-package nix-mode                                                                                                                                                                                              
  :ensure t                                                                                                                                                                                                        
  :mode "\\.nix\\'"                                                                                                                                                                                                
  :custom                                                                                                                                                                                                          
  (nix-indent-function #'nix-indent-line))  
```
