### ISSUE TITLE
add auto-mode-alist entries

### ISSUE THREAD

**Issue by bendlas** [NixOS/nix-mode#51]
It is common practice for emacs major modes, to add themselves to `auto-mode-alist`.
`nix-mode` seems to have lost this capability as part of https://github.com/NixOS/nix-mode/commit/dd49386cc7a2322dbf329d47b427ecf64ab600da
I noticed it, because my `*.nix` files stopped highlighting automatically.

What was the rationale for removing `global-nix-mode`?

Would you consider re-adding this option, or even just setting up `auto-mode-list` unconditionally (as is usual for other modes)? cc @matthewbauer

**Comment by matthewbauer** [comment]
Thanks. It used to be set correctly but somehow got removed in restructuring.
