### ISSUE TITLE
Indentation broken in melpa package?

### ISSUE THREAD

**Issue by GlennS** [NixOS/nix-mode#53]
Hi,

Installing the lastest melpa nix-mode package (20181015.100), indentiation appears to be completely broken?

This seems unlikely, so I assumed it must be something wrong with my configuration or one of my other packages. I've tried the following, but none of them made a difference:

 * Emacs 25.3 and Emacs 26.1
 * Removing all other packages except json-mode
 * Wiping most of my config
 * Setting `nix-indent-function` to `nix-indent-line`

If I visit a .nix file, I can see that nix-mode is enabled, but hitting `C-h` (highlight buffer) followed by `<TAB>` (indent) just moves everything to the left margin with no indentation.

The stripped-down config file I am testing with looks like this:

```
;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-archives
   (quote
    (("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "http://melpa.milkbox.net/packages/"))))
 '(package-selected-packages (quote (nix-mode json-mode))))

(provide `.emacs)
;;; .emacs ends here
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

Any suggestions?

I am thinking that my next attempt will be to manually install the latest master version from Github.

Regards,
Glenn

**Comment by matthewbauer** [comment]
That sounds like indent-relative behavior. I would make sure you are actually setting nix-indent-function correctly. It is buffer local so you will need to run set-variable in each buffer you open.

To make it the default:

```
M-x customize-variable<RET>nix-indent-function
```

Setting nix-indent-function there and clicking "State" followed by "1" to save permanently.

**Comment by GlennS** [comment]
Yes, that did the trick, thank you.
