### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by wedens** [NixOS/nix-mode#69]
There are some problems with handling empty lists and sets:
```nix
{
}
```
is being indented as
```
{
  }
```
and
```nix
{
x = [
];
}
````
as
```nix
{
  x = [
    ];
}
```

As soon as there is at least 1 element, it seems to work fine.

Also this it the reason why it behaves weirdly with `electric-pair-mode`.

Another case:
```nix
{
  a = {
    x1="abc";
  };
b = {
  x2 = 1;
};
}
```
is just left as is on attempt to indent. But if you add spaces to ` x1 = "abc"; `, it'll indent correctly.

**Comment by grahamc** [comment]
if I tab each I get:

```nix
{
  a = {
    x1="abc";
  };
  b = {
    x2 = 1;
  };
}
```
