### ISSUE TITLE
Incorrect indentation of multi-line strings with different indent

### ISSUE THREAD

**Issue by etu** [NixOS/nix-mode#77]
For example:
```nix
{
  foo = ''
    bar
      baz
    tux
  '';
}
```
is changed to
```nix
{
  foo = ''
    bar
    baz
    tux
  '';
}
```
but it should be exactly as it is as we don't want (?) it to change the indentation in strings more than to make sure that they aren't less indented than the first line?

cc @grahamc who reported this is #73 for opinions.

**Comment by matthewbauer** [comment]
Fixed in #79! Kudos to @j-piecuch
