### ISSUE TITLE
with is highlighted even when it appears as part of an identifier

### ISSUE THREAD

**Issue by IvanMalison** [NixOS/nix-mode#84]
![with_issue](https://user-images.githubusercontent.com/1246619/60215353-42478380-981c-11e9-93bf-543b3c82bf0f.png)

**Comment by matthewbauer** [comment]
I noticed this and forgot about it. Thanks for reminding me! I have a fix in https://github.com/NixOS/nix-mode/pull/85, please try it out.

We should also add some fontifcation tests as well.
