### ISSUE TITLE
json-mode not listed as dependency on MELPA

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nix-mode#92]
See https://melpa.org/#/nix-mode

This means we get this if we try to compile it

```
nix-drv-mode.el:19:1:Error: Cannot open load file: No such file or directory, json-mode
```

I couldn't figure out why it's not listed within 5 minutes...

**Comment by matthewbauer** [comment]
I'm not sure why it's missing. It's listed here:

https://github.com/NixOS/nix-mode/blob/master/Cask#L26

**Comment by etu** [comment]
Should be listed in the files https://github.com/NixOS/nix-mode/blob/master/nix-mode.el#L7

**Comment by akirak** [comment]
You have to add `json-mode` to the header of `nix-mode.el`, since it's the main file of the package.

Alternatively, you could make `nix-drv-mode` a separate package which I don't think is a good idea, or make the dependency optional, since you can use the built-in `js-mode` for browsing JSON.
