### ISSUE TITLE
Nix search paths at the end of the line breaks indentation of next line

### ISSUE THREAD

**Issue by terlar** [NixOS/nix-mode#94]
Example:
```nix
let
  nixpkgs = <nixpkgs>;
    wrongIndentedLine = true; 
in {
  ...
}
```

Now this example is not very useful, but there are a lot of use cases where you want to be able to use the search paths. E.g.:

```nix
{ config, ... }: {
  xdg.configFile."emacs/early-init.el".source = <emacs-config/early-init.el>;
    xdg.configFile."wronglyIndented.line".text = "yup";
}
```

**Comment by etu** [comment]
Which indentation function do you use?

**Comment by terlar** [comment]
Ah, forgot that there were 3 of them, I am using the `smie-indent-line`

**Comment by matthewbauer** [comment]
j-piecuch  should fix this
