### ISSUE TITLE
toggle for seeing hashes in paths

### ISSUE THREAD

**Issue by dangirsh** [NixOS/nix-mode#99]
Love this mode!

I'm wondering if this is a good idea: we could have a toggle that shows/hides the hash in `/nix/store/<hash>...` wherever they appear in a buffer. This would reduce the visual toll these hashes have.

There could also be an option to visually truncate the hashes, for cases when their values are actually useful to the user. 

I'm not yet sure what the best way to implement this is, but thought I'd throw up the idea. Ideally, an implementation would make it easy to expand any particular hash on demand.

We could call it `nix-glasses-mode`.

**Comment by matthewbauer** [comment]
nix-prettify-mode, based on guix-prettify-mode, does this (with `…`): https://github.com/NixOS/nix-mode/blob/master/nix-prettify-mode.el

**Comment by dangirsh** [comment]
Sweet. That escaped my mobile google-fu. Updated README.
